[package]
name = "ratatui-demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
ratatui = { version = "0.23", features = ["widget-calendar"] }

better-panic = "0.3"
time = "0.3"
